#!/usr/bin/env bash
# Exit immediately if a command exits with a non-zero status. This helps catch errors early.
set -e

# ==============================================================================
#                      ** SCRIPT EXPLANATION / README **
# ==============================================================================
#
# ## Purpose: Core QIIME 2 Amplicon Sequencing Pipeline
# 
# This script executes the standard QIIME 2 workflow, encompassing data import,
# DADA2 denoising, feature table summarization, phylogenetic tree construction,
# taxonomy assignment (using a SILVA classifier), and core diversity analysis.
# Checkpoints are used heavily, allowing the script to be run multiple times
# without re-running completed steps.
#
# ## Prerequisites:
# 1. **Conda Environment:** The `qiime2-2025.10` Conda environment must exist.
# 2. **FASTQ Files:** Primer-trimmed FASTQ files must be in the `trimmed_sequences/`
#    directory.
# 3. **Parameters:** The file `fastqc_reports_trimmed/qiime2_trunc_params.txt`
#    must exist, generated by `run_fastqc.sh`.
# 4. **Metadata:** The file `AGS_Project_metadata.tsv` must be present.
#
# ==============================================================================

# --- Configuration ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 🚨 USER-FILLABLE VARIABLE 🚨
PROJECT_NAME="AGS_Project" 
CONDA_ENV="qiime2-2025.10"

# Input/Output Paths
INPUT_DIR="${SCRIPT_DIR}/trimmed_sequences"
MANIFEST_FILE="${SCRIPT_DIR}/${PROJECT_NAME}_manifest.tsv"
METADATA_FILE="${SCRIPT_DIR}/${PROJECT_NAME}_metadata.tsv"
PARAMS_DIR="${SCRIPT_DIR}/fastqc_reports_trimmed"
PARAMS_FILE="${PARAMS_DIR}/qiime2_trunc_params.txt"
OUTPUT_DIR="${SCRIPT_DIR}/qiime2_analysis"

# Classifier Configuration
CLASSIFIER_DIR="${SCRIPT_DIR}"
CLASSIFIER_NAME="silva-138-99-nb-classifier.qza"
CLASSIFIER_PATH="${CLASSIFIER_DIR}/silva-138-99-nb-classifier.qza"
# Using the verified scikit-learn 1.4.2 compatible classifier URL
CLASSIFIER_URL="https://data.qiime2.org/classifiers/sklearn-1.4.2/silva/silva-138-99-nb-classifier.qza" 

# ------------------------------------------------------------------------------
# Primer Configuration (V4 Region Primers: 515F / 806R)
# ------------------------------------------------------------------------------
FWD_PRIMER="GTGCCAGCMGCCGCGGTAA"
REV_PRIMER="GGACTACHVGGGTWTCTAAT"

# --- Tool Check: realpath ---
if ! command -v realpath &> /dev/null; then
    echo "❌ FATAL ERROR: The 'realpath' command is not installed. It is required to generate absolute paths for the manifest file."
    exit 1
fi

# ------------------------------------------------------------------------------
# ## 1. Manifest File Generation 📝
# ------------------------------------------------------------------------------
echo "--- Generating QIIME 2 Manifest File: ${MANIFEST_FILE} ---"

# --- Dynamic Calculation of Expected Sample Count ---
EXPECTED_R1_COUNT=$(find "${INPUT_DIR}" -maxdepth 1 -name '*_R1_trimmed.fastq.gz' -print | wc -l | tr -d ' ')
echo "ℹ️ Found ${EXPECTED_R1_COUNT} R1 input files. This is the expected number of samples."

if [ "${EXPECTED_R1_COUNT}" -eq 0 ]; then
    echo "❌ FATAL ERROR: No R1 FASTQ files found in ${INPUT_DIR}. Check your input directory and file naming pattern."
    exit 1
fi
# ---------------------------------------------------

# --- Checkpoint Logic for Manifest ---
MANIFEST_NEEDS_REGENERATION=true

if [ -f "${MANIFEST_FILE}" ]; then
    LINE_COUNT=$(wc -l < "${MANIFEST_FILE}")
    
    if [ "${LINE_COUNT}" -gt 1 ]; then
        MANIFEST_SAMPLES=$((LINE_COUNT - 1))
        UNIQUE_SAMPLE_COUNT=$(awk 'NR > 1 {print $1}' "${MANIFEST_FILE}" | sort -u | wc -l | tr -d ' ')
        
        if [ "${UNIQUE_SAMPLE_COUNT}" -eq "${EXPECTED_R1_COUNT}" ] && [ "${MANIFEST_SAMPLES}" -eq "${EXPECTED_R1_COUNT}" ]; then
            echo "✅ Checkpoint: Manifest file found with the correct count (${EXPECTED_R1_COUNT} unique samples). Skipping generation."
            MANIFEST_NEEDS_REGENERATION=false
            
        elif [ "${MANIFEST_SAMPLES}" -ne "${UNIQUE_SAMPLE_COUNT}" ]; then
            echo "❌ Manifest Error: Found ${MANIFEST_SAMPLES} total entries but only ${UNIQUE_SAMPLE_COUNT} unique sample IDs. Duplicates detected. Forcing regeneration..."
            rm -f "${MANIFEST_FILE}" # Clean up the incorrect file
            
        else
            echo "⚠️ Manifest file found with ${UNIQUE_SAMPLE_COUNT} unique samples. Expected ${EXPECTED_R1_COUNT}. Forcing regeneration..."
            rm -f "${MANIFEST_FILE}" # Clean up the file with the wrong count
        fi
    else
        # File exists but is empty (only header or nothing)
        echo "⚠️ Manifest file found but is empty (only header). Regenerating..."
        rm -f "${MANIFEST_FILE}" # Clean up the empty file
    fi
fi

# --- Generation Block (Only runs if checkpoint failed or file didn't exist) ---
if [ "${MANIFEST_NEEDS_REGENERATION}" = true ]; then
    echo "Creating new manifest file..."
    printf "sample-id\tforward-absolute-filepath\treverse-absolute-filepath\n" > "${MANIFEST_FILE}"

    # Use find to locate only R1 files and ensure uniqueness with sort -u
    find "${INPUT_DIR}" -maxdepth 1 -name '*_R1_trimmed.fastq.gz' -print | sort -u | while IFS= read -r R1_PATH; do
        R1_FILENAME=$(basename "${R1_PATH}")
        SAMPLE_ID=$(echo "${R1_FILENAME}" | sed -E 's/^([A-Z0-9]+).*/\1/')
        R2_FILENAME=$(echo "${R1_FILENAME}" | sed 's/_R1_/_R2_/')
        R2_PATH="${INPUT_DIR}/${R2_FILENAME}"

        if [ -f "${R2_PATH}" ]; then
            R1_ABS_PATH=$(realpath "${R1_PATH}")
            R2_ABS_PATH=$(realpath "${R2_PATH}")
            
            printf "%s\t%s\t%s\n" "${SAMPLE_ID}" "${R1_ABS_PATH}" "${R2_ABS_PATH}" >> "${MANIFEST_FILE}"
        else
            echo "Warning: Missing paired R2 file for ${SAMPLE_ID} (${R2_FILENAME}). Skipping pair."
        fi
    done
    
    # Final confirmation check
    LINE_COUNT=$(wc -l < "${MANIFEST_FILE}")
    if [ "${LINE_COUNT}" -gt 1 ]; then
        SAMPLE_COUNT=$((LINE_COUNT - 1))
        echo "✅ Manifest file successfully created with ${SAMPLE_COUNT} samples at ${MANIFEST_FILE}."
    else
        echo "❌ FATAL ERROR: No paired FASTQ files could be processed into the manifest. Exiting."
        rm -f "${MANIFEST_FILE}" # Clean up the empty file
        exit 1
    fi
fi
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------
#---
## 2. Conda Environment Setup and Activation ⚙️
#---
echo "Activating Conda environment: $CONDA_ENV"
if command -v conda &> /dev/null; then
    CONDA_BASE=$(conda info --base)
    if [ -f "${CONDA_BASE}/etc/profile.d/conda.sh" ]; then
        source "${CONDA_BASE}/etc/profile.d/conda.sh"
    fi
    # Activate the environment
    conda activate $CONDA_ENV
    
    if [ $? -ne 0 ]; then
        echo "ERROR: Failed to activate Conda environment '${CONDA_ENV}'. Did you run installs.sh?"
        exit 1
    fi
    QIIME_COMMAND="qiime"
    echo "Environment activated. QIIME commands will be called directly."
else
    echo "ERROR: 'conda' command not found. Cannot proceed."
    exit 1
fi


# --- Reusable Checkpoint Function ---
# $1: Output file path
# $2...: Command to execute if file does not exist
run_qiime_step() {
    local output_file="$1"
    shift 
    
    if [ -f "$output_file" ]; then
        echo "✅ Checkpoint: $(basename "$output_file") already exists. Skipping step."
    else
        echo "⏳ Running command to create $(basename "$output_file")..."
        "$@"
        if [ $? -ne 0 ]; then 
            echo "❌ Error encountered creating $(basename "$output_file"). Exiting." 
            exit 1
        fi
        echo "✅ $(basename "$output_file") successfully created."
    fi
}
# ------------------------------------

#---
## 3. Classifier Download Check 🧬 (Optimized Checkpoint)
#---
echo "--- Checking for Taxonomy Classifier ---"

# FIX: Restore simple checkpoint logic now that the correct URL is in use.
if [ -f "${CLASSIFIER_PATH}" ]; then
    echo "✅ Checkpoint: Compatible classifier found at $(basename "${CLASSIFIER_PATH}"). Skipping download."
else
    echo "❌ Classifier not found. Attempting to download the compatible SILVA classifier..."
    mkdir -p "${CLASSIFIER_DIR}"
    
    if command -v wget &> /dev/null; then
        echo "Using wget to download classifier from ${CLASSIFIER_URL}..."
        wget -O "${CLASSIFIER_PATH}" "${CLASSIFIER_URL}"
    elif command -v curl &> /dev/null; then
        echo "Using curl to download classifier from ${CLASSIFIER_URL}..."
        curl -L "${CLASSIFIER_URL}" -o "${CLASSIFIER_PATH}"
    else
        echo "FATAL ERROR: Neither wget nor curl is installed. Cannot download classifier."
        exit 1
    fi
    
    if [ $? -ne 0 ]; then
        echo "❌ FATAL ERROR: Download failed. Check the URL and network connection."
        exit 1
    fi
    echo "✅ Successfully downloaded compatible classifier to ${CLASSIFIER_PATH}."
fi

#---
## 4. Parameter Extraction and Setup 🔬
#---
if [ ! -f "${PARAMS_FILE}" ]; then
    echo "Error: Truncation parameter file not found: ${PARAMS_FILE}"
    echo "Please run 'run_fastqc.sh' first."
    exit 1
fi

# Load R1_TRUNC_LEN and R2_TRUNC_LEN from the parameters file
source "${PARAMS_FILE}"
echo "Loaded truncation parameters: R1=${R1_TRUNC_LEN} bp, R2=${R2_TRUNC_LEN} bp"

# Check if values are sensible (non-zero)
if [ "${R1_TRUNC_LEN}" -eq 0 ] && [ "${R2_TRUNC_LEN}" -eq 0 ]; then
    echo "Error: Both R1 and R2 truncation lengths are 0. Check FastQC reports."
    exit 1
fi

# Create output directories
mkdir -p "${OUTPUT_DIR}"
echo "Created QIIME 2 output directory: ${OUTPUT_DIR}"


#---
## 5. QIIME 2 Pipeline Steps (DADA2) 💻
#---
echo "--- Starting QIIME 2 Pipeline (DADA2) ---"

# 5.1 Import Data
QZA_DEMUX="${OUTPUT_DIR}/01_demultiplexed_seqs.qza"
echo "1. Importing paired-end FASTQ data..."
run_qiime_step "${QZA_DEMUX}" \
  ${QIIME_COMMAND} tools import \
    --type 'SampleData[PairedEndSequencesWithQuality]' \
    --input-path "${MANIFEST_FILE}" \
    --output-path "${QZA_DEMUX}" \
    --input-format PairedEndFastqManifestPhred33V2


# 5.2 Visualize Demultiplexed Sequences
QZV_DEMUX="${OUTPUT_DIR}/02_demux_summary.qzv"
echo "2. Visualizing demultiplexed sequences..."
if [ ! -f "${QZV_DEMUX}" ]; then
    ${QIIME_COMMAND} demux summarize \
      --i-data "${QZA_DEMUX}" \
      --o-visualization "${QZV_DEMUX}" || echo "Warning: Demux visualization failed. Continuing..."
else
    echo "✅ Checkpoint: $(basename "${QZV_DEMUX}") already exists. Skipping step."
fi


# 5.3 Denoise and Dereplicate using DADA2
QZA_TABLE="${OUTPUT_DIR}/03_feature_table.qza"
QZA_REP_SEQS="${OUTPUT_DIR}/04_rep_seqs.qza"
QZA_DADA2_STATS="${OUTPUT_DIR}/05_dada2_stats.qza"

echo "3. Running DADA2 denoising with trunc-len-f ${R1_TRUNC_LEN} and trunc-len-r ${R2_TRUNC_LEN}..."
if [ ! -f "${QZA_TABLE}" ]; then
    ${QIIME_COMMAND} dada2 denoise-paired \
      --i-demultiplexed-seqs "${QZA_DEMUX}" \
      --p-trunc-len-f "${R1_TRUNC_LEN}" \
      --p-trunc-len-r "${R2_TRUNC_LEN}" \
      --o-table "${QZA_TABLE}" \
      --o-representative-sequences "${QZA_REP_SEQS}" \
      --o-denoising-stats "${QZA_DADA2_STATS}" \
      --o-base-transition-stats "${OUTPUT_DIR}/06_dada2_transition_stats.qza" \
      --verbose
    if [ $? -ne 0 ]; then echo "❌ Error in DADA2 Denoising. Exiting."; exit 1; fi
    echo "✅ DADA2 artifacts successfully created."
else
    echo "✅ Checkpoint: $(basename "${QZA_TABLE}") already exists. Skipping DADA2 step."
fi


# 5.4 Generate Summaries for Review
echo "4. Generating Feature Table and Representative Sequences summaries..."

QZV_TABLE_SUMMARY="${OUTPUT_DIR}/07_feature_table_summary.qzv"
run_qiime_step "${QZV_TABLE_SUMMARY}" \
  ${QIIME_COMMAND} feature-table summarize \
    --i-table "${QZA_TABLE}" \
    --o-visualization "${QZV_TABLE_SUMMARY}"

QZV_REP_SEQS_SUMMARY="${OUTPUT_DIR}/08_rep_seqs_summary.qzv"
run_qiime_step "${QZV_REP_SEQS_SUMMARY}" \
  ${QIIME_COMMAND} feature-table tabulate-seqs \
    --i-data "${QZA_REP_SEQS}" \
    --o-visualization "${QZV_REP_SEQS_SUMMARY}"


# 5.5 Build Phylogenetic Tree
echo "--- 5. Building Phylogenetic Tree ---"

# 5.5a. Aligning
QZA_ALIGNMENT="${OUTPUT_DIR}/09_aligned_rep_seqs.qza"
run_qiime_step "${QZA_ALIGNMENT}" \
  ${QIIME_COMMAND} alignment mafft \
    --i-sequences "${QZA_REP_SEQS}" \
    --o-alignment "${QZA_ALIGNMENT}"

# 5.5b. Masking
QZA_MASKED_ALIGNMENT="${OUTPUT_DIR}/10_masked_aligned_rep_seqs.qza"
run_qiime_step "${QZA_MASKED_ALIGNMENT}" \
  ${QIIME_COMMAND} alignment mask \
    --i-alignment "${QZA_ALIGNMENT}" \
    --o-masked-alignment "${QZA_MASKED_ALIGNMENT}"

# 5.5c. Building tree
QZA_UNROOTED_TREE="${OUTPUT_DIR}/11_unrooted_tree.qza"
run_qiime_step "${QZA_UNROOTED_TREE}" \
  ${QIIME_COMMAND} phylogeny fasttree \
    --i-alignment "${QZA_MASKED_ALIGNMENT}" \
    --o-tree "${QZA_UNROOTED_TREE}"

# 5.5d. Rooting the tree
QZA_ROOTED_TREE="${OUTPUT_DIR}/12_rooted_tree.qza"
run_qiime_step "${QZA_ROOTED_TREE}" \
  ${QIIME_COMMAND} phylogeny midpoint-root \
    --i-tree "${QZA_UNROOTED_TREE}" \
    --o-rooted-tree "${QZA_ROOTED_TREE}"


# 5.6 Taxonomy Assignment
echo "--- 6. Taxonomy Assignment ---"

# 5.6a. Assigning taxonomy
QZA_TAXONOMY="${OUTPUT_DIR}/13_taxonomy.qza"
run_qiime_step "${QZA_TAXONOMY}" \
  ${QIIME_COMMAND} feature-classifier classify-sklearn \
    --i-reads "${QZA_REP_SEQS}" \
    --i-classifier "${CLASSIFIER_PATH}" \
    --o-classification "${QZA_TAXONOMY}"

# 5.6b. Generating Taxonomy visualization
QZV_TAXONOMY_TABULATED="${OUTPUT_DIR}/14_taxonomy_tabulated.qzv"
run_qiime_step "${QZV_TAXONOMY_TABULATED}" \
  ${QIIME_COMMAND} metadata tabulate \
    --m-input-file "${QZA_TAXONOMY}" \
    --o-visualization "${QZV_TAXONOMY_TABULATED}"

# 5.6c. Generating Taxa Barplots
QZV_TAXA_BARPLOTS="${OUTPUT_DIR}/15_taxa_barplots.qzv"
echo "6c. Generating Taxa Barplots..."

if [ ! -f "${METADATA_FILE}" ]; then
    echo "❌ WARNING: Metadata file not found: ${METADATA_FILE}. Skipping Taxa Barplots."
else
    # We check the checkpoint file for 6c
    if [ ! -f "${QZV_TAXA_BARPLOTS}" ]; then
        ${QIIME_COMMAND} taxa barplot \
            --i-table "${QZA_TABLE}" \
            --i-taxonomy "${QZA_TAXONOMY}" \
            --m-metadata-file "${METADATA_FILE}" \
            --o-visualization "${QZV_TAXA_BARPLOTS}"
        if [ $? -ne 0 ]; then echo "❌ Error: Taxa barplot generation failed. Continuing..."; fi
    else
        echo "✅ Checkpoint: $(basename "${QZV_TAXA_BARPLOTS}") already exists. Skipping step."
    fi
fi

#---
## 6. Alpha and Beta Diversity Analysis 📊
#---
echo "--- 7. Alpha and Beta Diversity Analysis ---"

# Variables for Step 6
ALPHA_BETA_DIV="${OUTPUT_DIR}/diversity-core-metrics-phylogenetic"
SAMPLE_READ_COUNTS_FILE="${OUTPUT_DIR}/03_sample_read_counts.tsv"

# Temporary variables for generating the read counts file
TEMP_EXPORT_DIR="${OUTPUT_DIR}/temp_export_dir_export"
TEMP_BIOM_FILE="${TEMP_EXPORT_DIR}/feature-table.biom"
SAMPLING_DEPTH=0 # Initialized to 0, will be set by user input

# --- 6a. Create Sample Read Counts File (Fixed for reliable parsing) ---
echo "6a. Exporting feature table and calculating total reads per sample..."

if [ ! -f "${SAMPLE_READ_COUNTS_FILE}" ]; then
    echo "⏳ Exporting feature table artifact to BIOM format..."
    mkdir -p "${TEMP_EXPORT_DIR}"

    # Export QIIME 2 table to BIOM format
    ${QIIME_COMMAND} tools export \
        --input-path "${QZA_TABLE}" \
        --output-path "${TEMP_EXPORT_DIR}"

    if [ ! -f "${TEMP_BIOM_FILE}" ]; then
        echo "❌ ERROR: QIIME tools export failed. The BIOM file was not created. Cannot proceed."
        rm -rf "${TEMP_EXPORT_DIR}"
        exit 1
    fi

    echo "⏳ Summarizing BIOM table to generate sample read count file..."
    
    # Use the reliable '--output-counts' flag from biom summarize-table
    conda run -n ${CONDA_ENV} biom summarize-table \
        -i "${TEMP_BIOM_FILE}" \
        --output-counts \
        > "${SAMPLE_READ_COUNTS_FILE}.temp" 2>&1

    # Format the output file: replace first line, and rename columns
    echo -e "sample-id\tTotal_Reads" > "${SAMPLE_READ_COUNTS_FILE}"
    tail -n +2 "${SAMPLE_READ_COUNTS_FILE}.temp" >> "${SAMPLE_READ_COUNTS_FILE}"
    
    rm -f "${SAMPLE_READ_COUNTS_FILE}.temp"
    rm -rf "${TEMP_EXPORT_DIR}"

    if [ $(wc -l < "${SAMPLE_READ_COUNTS_FILE}") -le 1 ]; then
        echo "❌ FATAL ERROR: Read counts file is still empty or contains only the header after creation."
        echo "Please manually inspect the BIOM file for sample counts."
        exit 1
    fi

    echo "✅ Sample read counts saved to: ${SAMPLE_READ_COUNTS_FILE}"
else
    echo "✅ Sample read counts file already exists: ${SAMPLE_READ_COUNTS_FILE}. Skipping creation."
fi


# --- 6b. Interactive Sampling Depth Prompt ---
echo -e "\n-------------------------------------------------"
echo "### ACTION REQUIRED: DETERMINE SAMPLING DEPTH ###"
echo "Please review the total read counts per sample saved in:"
echo "➡️ ${SAMPLE_READ_COUNTS_FILE}"
echo "Use this file to determine the appropriate **sampling depth** for your diversity analysis."


echo -e "\nℹ️ QIIME 2 requires a sampling depth for diversity analysis."
read -r -p "Enter the desired sampling depth: " SAMPLING_DEPTH

if ! [[ "$SAMPLING_DEPTH" =~ ^[0-9]+$ ]] || [ "$SAMPLING_DEPTH" -le 0 ]; then
    echo "❌ Invalid sampling depth entered. Exiting."
    exit 1
fi

# --- 6c. Run Core Metrics ---
if [ ! -f "${METADATA_FILE}" ]; then
    echo "❌ FATAL ERROR: Metadata file required for diversity analysis not found: ${METADATA_FILE}"
    echo "Please create a valid QIIME 2 sample-metadata.tsv file."
    exit 1
fi

# Use a guaranteed QIIME 2 output artifact as the checkpoint
RAREFIED_TABLE_QZA="${ALPHA_BETA_DIV}/rarefied_table.qza"

echo -e "\nRunning Core Metrics with user-defined sampling depth: ${SAMPLING_DEPTH}"
run_qiime_step "${RAREFIED_TABLE_QZA}" \
  ${QIIME_COMMAND} diversity core-metrics-phylogenetic \
    --i-phylogeny "${QZA_ROOTED_TREE}" \
    --i-table "${QZA_TABLE}" \
    --p-sampling-depth "${SAMPLING_DEPTH}" \
    --m-metadata-file "${METADATA_FILE}" \
    --output-dir "${ALPHA_BETA_DIV}"

# --- Final Summary ---
echo "---"
echo "QIIME 2 Pipeline Complete."
echo "Results saved in the '${OUTPUT_DIR}' directory."
echo "Next Steps: View your results by opening the .qzv files in a browser using:"
echo "➡️ qiime tools view <path_to_qzv_file>"